### ISSUE TITLE
Suggestion Use cask :)

### ISSUE THREAD

**Issue by AdrieanKhisbe** [dpsutton/resize-window#1]
> As soon as it gets polished a little further, it will hopefully be accepted to ELPA or something (I'm not too sure about all of the differences, ELPA, MELPA, marmalade, etc.

To do so, I recommend you to set up _cask_ and over this article of it's creator: 
http://rejeep.github.io/emacs/cask/ert/ert-runner/ert-async/ecukes/testing/travis/2014/01/09/various-testing-tools-in-emacs.html

If this interest you, I'll suggest you then to use 
https://github.com/AdrieanKhisbe/cask-package-toolset.el. A tool I created to help you set up CI for your emacs package. :)

_Don't hesitate to pose me any question :)_

**Comment by dpsutton** [comment]
I'm glad you brought this up. I am researching it as we speak. I'd love to have a test suite as well. 

Once confusing thing that i've found is that I tried to run the tests in cask (make test) after cloning the repo, but all tests failed. But this is because it could not find zop-to-char, saying that the file did not exist in .emacs.d/elpa/zop-to-char... . However, it most certainly does exist. There must be a permissions issue somewhere.

But I am working on it and thanks for the suggestion.

**Comment by AdrieanKhisbe** [comment]
Did you run `cask install` before to retrieve your dependancies?

(also you should had `zop-to-char` as a dependancy in the `Cask` file.
I can be more helpful if you push your code in progress in a `dev` branch :) )

**Comment by AdrieanKhisbe** [comment]
(cask install the dependancy localy, in your project directory, `.cask/24.5.1/elpa/......`)

**Comment by dpsutton** [comment]
sorry, the error messages about zop-to-char were not from my package but from running the tests in cask itself.

I used homebrew to install cask but the version is outdated, 0.7.3, which still has poor error reporting, reporting unbalanced parentheses in the package requires. When i just used the up-to-date repo version, I'm getting `Package lacks a footer line in file resize-window.el`.

However, my file looks like this:
`(provide 'resize-window)
;;; resize-window.el ends here`

I'm not too sure how to progress right now. I'm just running `cask` (or actually `~/Drive/cask/bin/cask`) in this directory to see what it does

**Comment by dpsutton** [comment]
i've pushed to a branch named cask. do you see anything wrong with that footer by any chance? it seems just fine to me

**Comment by AdrieanKhisbe** [comment]
I fork, rebased on master, and made few tweak in the header. Then It worked. :)

```
$ cask install
Making version-control local to el-mock-autoloads.el while let-bound!
Wrote /Users/abecchis/git/-tmp-fork/resize-window/.cask/24.5.1/elpa/el-mock-20150906.321/el-mock-autoloads.el
Wrote /Users/abecchis/git/-tmp-fork/resize-window/.cask/24.5.1/elpa/shut-up-20150423.522/shut-up-autoloads.el
Wrote /Users/abecchis/git/-tmp-fork/resize-window/.cask/24.5.1/elpa/dash-20151021.113/dash-autoloads.el
Wrote /Users/abecchis/git/-tmp-fork/resize-window/.cask/24.5.1/elpa/s-20150924.406/s-autoloads.el
Wrote /Users/abecchis/git/-tmp-fork/resize-window/.cask/24.5.1/elpa/ansi-20150703.126/ansi-autoloads.el
Wrote /Users/abecchis/git/-tmp-fork/resize-window/.cask/24.5.1/elpa/f-20151113.123/f-autoloads.el
Wrote /Users/abecchis/git/-tmp-fork/resize-window/.cask/24.5.1/elpa/commander-20140120.1052/commander-autoloads.el
Wrote /Users/abecchis/git/-tmp-fork/resize-window/.cask/24.5.1/elpa/ert-runner-20151023.113/ert-runner-autoloads.el
Wrote /Users/abecchis/git/-tmp-fork/resize-window/.cask/24.5.1/elpa/espuds-20151114.759/espuds-autoloads.el
Wrote /Users/abecchis/git/-tmp-fork/resize-window/.cask/24.5.1/elpa/ecukes-20150717.648/ecukes-autoloads.el
```

**Comment by AdrieanKhisbe** [comment]
I can set up all the CI quickly if you want.
scaffolding the test and co.  :)

If you prefer to do it yourself tell me :)

**Comment by dpsutton** [comment]
holy moly that's incredible.
I would love to see how you scaffold the tests. I've never done that before in elisp, especially with giving keystrokes to read-key and such. I would love to see what you do.

I have one question though. In the travis.yml file (i think) you have +sudo: required. Can you tell me why sudo is required right before a curl script? I'm sure its standard but I just don't understand that point yet

**Comment by AdrieanKhisbe** [comment]
The `sudo`is required because it relly on an version of EVM that needed it.

I'm on my way to refactor https://github.com/AdrieanKhisbe/cask-package-toolset.el with latest version, waiting to rejeep script to come under the hood of cpt.

cf: https://github.com/AdrieanKhisbe/cask-package-toolset.el/issues/3

**Comment by AdrieanKhisbe** [comment]
about scaffolding of test I just create minimum file:

for example of a test: https://github.com/AdrieanKhisbe/omni-log.el/blob/master/test/omni-log-test.el

Here is some reeding from rejeep:
- [testing in emacs](http://rejeep.github.io/emacs/testing/cask/ecukes/ert-runner/2013/09/24/testing-in-emacs.html)
- [Unit Testing in emacs](http://rejeep.github.io/emacs/testing/cask/ert-runner/2013/09/26/unit-testing-in-emacs.html)
- [Integration Testing](http://rejeep.github.io/emacs/testing/cask/ecukes/2013/10/20/integration-testing-in-emacs.html)

**Comment by dpsutton** [comment]
excellent. I'll dig through these tonight after work. You are super helpful and thanks for showing me how to make my code in-line with what other lisp developers would expect.

**Comment by AdrieanKhisbe** [comment]
you're welcome :)

**Comment by AdrieanKhisbe** [comment]
Do you want me to create the melpa recipe so that resize-window is it's available on MEPLA: http://melpa.org/#/  ? :)

**Comment by dpsutton** [comment]
Honestly, if you would leave some notes about what you've done I would love to type most of this up. There are so many moving parts outside of just the code that are fascinating. Would love to see a walk through start to finish

**Comment by dpsutton** [comment]
and by the above i mean I would absolutely love for you to create the melpa recipe

**Comment by AdrieanKhisbe** [comment]
Will do like I did for cask package in the PR.
(and I sure will have to write this long reported blog article about [cpt](https://github.com/AdrieanKhisbe/cask-package-toolset.el))

**Comment by dpsutton** [comment]
i will be poring over your repo tonight. I see that all of the skeleton stuff was generated by this? If so that's very handy.

**Comment by AdrieanKhisbe** [comment]
- fork melpa
- create branch `git co -b recipes/resize-window`
- get recipe with 
  `
      $ cask exec package-toolset melpa-recipe -g dpsutton/resize-window
      (resize-window :fetcher github :repo "dpsutton/resize-window")
  `
- put it in melpa fork, `recipes/resize-window`, add it, commit, push it. 
- do a merge request to melpa repo
- wait for input

And here is the PR: 
https://github.com/milkypostman/melpa/pull/3324

**Comment by dpsutton** [comment]
hi. I'm testing the following code:

```
(defun rw-execute-action (choice &optional scaled)
  "Given a CHOICE, grab values out of the alist.
If SCALED, then call action with the rw-capital-argument."
  ;; (char function description)
  (let ((action (cadr choice))
        (description (car (cdr (cdr choice)))))
    (if scaled
        (funcall action rw-capital-argument)
      (funcall action))
    (unless (equal (car choice) ??)
      (message "%s" description))))
```

Note that this calls to message. 

```
(ert-deftest should-execute-and-display-message ()
  (let ((choice '(?n (lambda () (setq executed t)) "doc" nil))
        (executed)
        (message-received ""))
    (rw-execute-action choice)
    (should (equal executed t))))
```

This code is testing it, but i'm unsure of how to test the call to message. At the moment, it is popping up in the terminal when i run `cask exec ert-runner`. Do you know of a good solution to this problem, or am i going about it in the wrong way?

Previously i had tried to bind message to a lambda `(lambda (m) (setq message-received m))` but this did not help.

**Comment by dpsutton** [comment]
hi. 

If you're still willing to listen a little bit, it looks like travis cannot build emacs from master at the moment. You have one of the build tasks as `- EVM_EMACS=emacs-git-snapshot`. This seems to build emacs from source but it seems to be missing some dependencies:

```
checking whether make supports nested variables... (cached) yes
checking whether ln -s works for files in the same directory... yes
checking for install-info... /usr/sbin/install-info
checking for gzip... /bin/gzip
checking for paxctl... no
checking for setfattr... no
configure: error: You do not seem to have makeinfo >= 4.7, and your
source tree does not seem to have pre-built manuals in the 'info' directory.
Either install a suitable version of makeinfo, or re-run configure
with the '--without-makeinfo' option to build without the manuals. 
The command "evm install $EVM_EMACS --use --skip" failed and exited with 1 during .
Your build has been stopped.
```

Have you ever encountered this? and do you know what might be the best way to proceed?

**Comment by AdrieanKhisbe** [comment]
about the test of message, if I remember well, when I add to test for it, 
it's was more in integration test with ecukes.
I had a look to my test in my packagge (_i haven't done ert for month_), and the more similar I found was this: https://github.com/AdrieanKhisbe/omni-log.el/blob/master/test/omni-log-test.el#L20-L25

**Comment by AdrieanKhisbe** [comment]
about snapshot, I usely don't worry about it, most of the time it doesn't manage to build. (which is unrelated for the package).
This might be fix, when _cpt_ will be relying on the latest EVM (with updated recipes for travis)

**Comment by AdrieanKhisbe** [comment]
after some reserch you shoud use: `with-output-to-temp-buffer`

```
with-output-to-temp-buffer is a Lisp macro in `subr.el'.

(with-output-to-temp-buffer BUFNAME &rest BODY)

Bind `standard-output' to buffer BUFNAME, eval BODY, then show that buffer.

This construct makes buffer BUFNAME empty before running BODY.
It does not make the buffer current for BODY.
Instead it binds `standard-output' to that buffer, so that output
generated with `prin1' and similar functions in BODY goes into
the buffer.

At the end of BODY, this marks buffer BUFNAME unmodified and displays
it in a window, but does not select it.  The normal way to do this is
by calling `display-buffer', then running `temp-buffer-show-hook'.
However, if `temp-buffer-show-function' is non-nil, it calls that
function instead (and does not run `temp-buffer-show-hook').  The
function gets one argument, the buffer to display.

The return value of `with-output-to-temp-buffer' is the value of the
last form in BODY.  If BODY does not finish normally, the buffer
BUFNAME is not displayed.

This runs the hook `temp-buffer-setup-hook' before BODY,
with the buffer BUFNAME temporarily current.  It runs the hook
`temp-buffer-show-hook' after displaying buffer BUFNAME, with that
buffer temporarily current, and the window that was used to display it
temporarily selected.  But it doesn't run `temp-buffer-show-hook'
if it uses `temp-buffer-show-function'.

By default, the setup hook puts the buffer into Help mode before running BODY.
If BODY does not change the major mode, the show hook makes the buffer
read-only, and scans it for function and variable names to make them into
clickable cross-references.

See the related form `with-temp-buffer-window'.

```
