### ISSUE TITLE
maximize a window?

### ISSUE THREAD

**Issue by futurist** [dpsutton/resize-window#10]
Sometimes there's a need for **maximize** a window, and restore it.

Can this lib do this type of job?

**Comment by dpsutton** [comment]
Probably. you could add a simple command for this if you add your own custom actions
`(?1 delete-other-windows " Delete other windows" nil)` is how you would add this.

The ?1 is the character to listen to, and I picked ?1 to mimic `C-x 1` to kill all other windows. The function called is the delete other windows function, doc string, and then the allow capitals to nil since there is no notion of capital one.

So in your init you could put the following:
`(push '(?1 delete-other-windows " Delete other windows" nil) resize-window-dispatch-alist)`

Now restore would add some other functionality. If you want to open an issue, I could work on a feature like so:

When you run the ?1 command, it pushes the window config into a var, and then you could call restore and it will pop from a list of pushed window states. 

So I'm not sure which of the two you want (dumb delete other windows or a smarter delete other windows and possibility of restoring window configuration) but that seems like a neat feature either way. The former can be done now, the latter would require some internal state.

**Comment by dpsutton** [comment]
@futurist I've implemented your feature:

press `k` to kill all but the current window. This pushes the window configuration into a stack and makes the current window the central window.

press `y` to "yank" back from the window configuration stack.

**Comment by futurist** [comment]
@dpsutton Maybe I'm not say that clearly, I'm using below code for myself:
```elisp
(defun my-max-window-size (restore)
  "Max window size of window."
  (interactive "P")
  (let* ((win (or
               (get-buffer-window "*Completions*")
               (get-buffer-window "*Ido Completions*")
               (get-buffer-window nil))) size)
    (when win
      (if restore
          (balance-windows nil)
        (setq size (window-resizable win 200))
        (window-resize win size))
      )
    )
  )
```

The `window-resizable` can return a max size a window can be reached, 

And `balance-windows` can do restore thing similarly.

Can you use this feature?

**Comment by futurist** [comment]
I'm binding into `C-x C-6`, pressed will max the window (not kill others), and `C-u C-x C-6` will restore all.

**Comment by dpsutton** [comment]
So this would make the window as large as possible but not make the other windows go away? Is this preferable to killing the windows and then restoring them?

**Comment by dpsutton** [comment]
But i think you could easily hook this up. If you look in the code, there is a distinction between capital and lowercase functions in what argument they get. You could have your function take an optional parameter (which it kinda does), and have it dispatch with that

`(push (?p my-max-window-size "Collapse or expand window" t) resize-window-dispatch-alist)`

And when you hit `p`, it would collapse, and configure it when its given a parameter, to enlarge it. This will be triggered when you hit `P`.  The optional argument should just inspect for truthy, so it would be just like your variable `restore` in your function.

**Comment by dpsutton** [comment]
@futurist did my comment address your concerns? I'm wondering if i've given you enough to make your own addition or if I need to add some code to make it amenable for your uses.

**Comment by futurist** [comment]
I've tried the code:
```
(push (?p my-max-window-size "Collapse or expand window" t) resize-window-dispatch-alist)
```

And show error:

> cons: Invalid function: 112

**Comment by futurist** [comment]
How the delete and restore feature compared with `winner-undo` and `winner-redo` ?

I've used these functions for manage window...

**Comment by dpsutton** [comment]
I'm not familiar with those. I'm gonna work with your `my-max-window-size` functions tomorrow morning as it is quite late here now. I hope I can help you out. But thanks for looking at my code so far :)

**Comment by dpsutton** [comment]
@futurist 
> cons: invalid function: 112

112 is the integer described by ?p. You need to quote that list.
`(push '(?p my-max-window-size "Collapse or expand window" t) resize-window-dispatch-alist)`

note the quote before the list you are adding. you want to add the list, and you code "evaluates" the list and tries to add the result.

**Comment by futurist** [comment]
Oh, the function now activated, but below error throw:

```
resize-window--execute-action: Wrong number of arguments: (lambda (restore) "Max window size of window." (interactive "P") (let* ((win (or (get-buffer-window "*Completions*") (get-buffer-window "*Ido Completions*") (get-buffer-window nil))) size) (if win (progn (setq size (window-resizable win 2000)) (if (or restore (= size 0)) (balance-windows nil) (window-resize win size)))))), 0
```

I can remove the `restore` args, but the problem is that resize-window hangs in this situation, and the buffer remains gray, cannot restore from `resize-window` status.

**Comment by mordonez-me** [comment]
When I try to restore I get the following error:

Invalid function: (config (resize-window--window-pop))

**Comment by dpsutton** [comment]
@mordonez-me I think I can see what's going on. I'm using a macro `when-let`. I think this may only exist in emacs 25+.

I just pushed a patch and a new release which should hopefully fix that up for you.

**Comment by dpsutton** [comment]
created release 0.5 to solve that problem.

**Comment by mordonez-me** [comment]
Thank you @dpsutton
