### ISSUE TITLE
Update prefix

### ISSUE THREAD

**Issue by AdrieanKhisbe** [dpsutton/resize-window#3]
To get on melpa you need to update the prefixe, cf https://github.com/milkypostman/melpa/pull/3324

(if you want me to do it tell me)

**Comment by dpsutton** [comment]
i've updated this. thanks for the heads up and getting things rolling with melpa.

**Comment by AdrieanKhisbe** [comment]
you're welcome

**Comment by AdrieanKhisbe** [comment]
I think that now you can tag it as `v.0.1.0`, the first release! :) 
:tada:
