### ISSUE TITLE
Overlay stuck when navigating back to Emacs using mouse

### ISSUE THREAD

**Issue by john-patterson** [dpsutton/resize-window#6]
When in resize mode, if the user navigates out of the emacs process and clicks back into the emacs process using the mouse, there is an error and the overlay is stuck on the screen.

![image](https://cloud.githubusercontent.com/assets/17716252/15190817/8afd4fac-1777-11e6-9029-f5e86d106d9b.png)

Environment:
Windows 7 Pro SP1
GNU Emacs 24.5.1 (i686-pc-mingw32) of 2015-04-11 on LEG570
Fundamental & WhichKey modes are on.

**Comment by dpsutton** [comment]
solid bug. I'll look into this

**Comment by john-patterson** [comment]
Issue is resolved.
